# Generated by Django 3.0.4 on 2020-03-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0004_auto_20200330_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
