# Generated by Django 3.0.4 on 2020-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0013_auto_20200409_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='--/--/----', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='--:--', max_length=100),
        ),
    ]
